# -*- coding: utf-8 -*-
"""Generadores de Caos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19eyVzH6a39ItGnvoxnIvn_e8_vm7AY-h
"""

import numpy as np
import matplotlib.pyplot as plt
import random
import imageio
from matplotlib.animation import FuncAnimation

def juego_caos(N, v):
  # Seleccionamos un punto aleatorio
  x, y = random.random(), random.random()
  # Creamos dos listas para guardar los puntos generados por las iteraciones
  lista_x = []
  lista_y = []
  # Realizamos la iteración
  for i in range(N):
    # obtenemos un vertice aleatorio
    rx, ry = random.choice(v)
    # calculamos el punto medio entre el vértice y el punto anterior
    x = (rx + x)/2
    y = (ry + y)/2
    # guardamos los puntos en las listas
    lista_x.append(x)
    lista_y.append(y)
  return lista_x, lista_y

"""# Triángulo de Serpinsky

1. Programar y utilizar el juego del caos de tres vértices para generar un triángulo de Sierpinsky, usando 10,000 puntos de una serie aleatoria con valores {1,2,3}.

## Triángulo equilátero
"""

# Usamos el juego del caos para obtener el triangulo de Serpinsky

# Definimos el número de puntos
N = 10000

# Creamos dos listas para guardar los puntos generados por las iteraciones
lista_x = []
lista_y = []

# Definimos los vértices que delimiten al triángulo
v = [[0,0],[1,0],[0.5,0.5*np.sqrt(3)]]

# Seleccionamos un punto aleatorio
x, y = random.random(), random.random()

# Realizamos la iteración
for i in range(N):
  # obtenemos un vertice aleatorio
  rx, ry = random.choice(v)
  # calculamos el punto medio entre el vértice y el punto anterior
  x = (rx + x)/2
  y = (ry + y)/2
  # guardamos los puntos en las listas
  lista_x.append(x)
  lista_y.append(y)

# Graficamos el triángulo de Serpinsky
plt.title('Triángulo de Serpinsky')
plt.scatter(lista_x, lista_y, s=1)
plt.show()

# Usamos el juego del caos para obtener el triangulo de Serpinsky

# Definimos el número de puntos
N = 10000

# Creamos dos listas para guardar los puntos generados por las iteraciones
lista_x = []
lista_y = []

# Definimos los vértices que delimiten al triángulo
v = [[0,0],[1,0],[0.2,1]]

# Seleccionamos un punto aleatorio
x, y = random.random(), random.random()

# Realizamos la iteración
for i in range(N):
  # obtenemos un vertice aleatorio
  rx, ry = random.choice(v)
  # calculamos el punto medio entre el vértice y el punto anterior
  x = (rx + x)/2
  y = (ry + y)/2
  # guardamos los puntos en las listas
  lista_x.append(x)
  lista_y.append(y)

# Graficamos el triángulo de Serpinsky
plt.title('Triángulo de Serpinsky')
plt.scatter(lista_x, lista_y, s=1)
plt.show()

# Generamos un gif que muestre cada que se agrega un punto al gráfico
fig, ax = plt.subplots()
ax.set_xlim(0,1)
ax.set_ylim(0,1)

def animate(i):
    ax.clear()
    ax.scatter(lista_x[:i], lista_y[:i], s=1) # Added s=1 for sharper points in the animation
    ax.set_xlim(0,1)
    ax.set_ylim(0,1)

anim = FuncAnimation(fig, animate, frames=len(lista_x), interval=1)
anim.save('triangulo.gif', writer='pillow') # Changed writer to pillow

"""# Boxcounting

2. Programar y utilizar un algoritmo de "conteo de cajas" (box counting) para encontrar la dimensión fractal del triángulo graficado arriba.
"""

# Implementamos el algortimo de box counting

def count_occup_boxes(grid, e):
    """
    Cuenta la cantidad de cajas de lado e que cubren el grafo.
    e : lado de la caja (box size)
    """
    rows, cols = grid.shape
    occup_count = 0
    for r in range(0, rows, e):
        for c in range(0, cols, e):
            # Checar si la celda está ocupada
            if np.any(grid[r:r+e, c:c+e] > 0):
                occup_count += 1
    return occup_count

# Definimos un rango de tamaños para las cajas (potencias de 2, pues haremos un log-log)
e_s = [2**i for i in range(int(np.log2(min(grid.shape))))]

# Calculamos la cantidad de cajas para cada tamaño
occupied_counts = [count_occup_boxes(grid, box_size) for box_size in e_s]

# Quitamos los tamaños en los que no hubieron cajas ocupadas
valid_indices = [i for i, count in enumerate(occupied_counts) if count > 0]
valid_e_s = [e_s[i] for i in valid_indices]
valid_occup_counts = [occupied_counts[i] for i in valid_indices]


# Calculate log-log values
log_box_sizes = np.log(1 / np.array(valid_e_s))
log_occup_counts = np.log(np.array(valid_occup_counts))

# Realizamos un ajuste lineal para calcular la dimensión fractal que es D = log(N)/log(1/e)
slope, intercept = np.polyfit(log_box_sizes, log_occup_counts, 1)
fractal_dimension = slope

print(f"Calculated Fractal Dimension: {fractal_dimension}")

# Graficamos la gráfica log-log
plt.figure(figsize=(8, 6))
plt.plot(log_box_sizes, log_occup_counts, 'o', label='Datos')
plt.plot(log_box_sizes, slope * log_box_sizes + intercept, 'r-', label=f'Ajuste Lineal (Dimension = {fractal_dimension:.2f})')
plt.xlabel('log(1 / e)')
plt.ylabel('log(N(e))')
plt.title('Método de Box-Counting para la Dimensión Fractal')
plt.legend()
plt.grid(True)
plt.show()

"""**Referencias**
1. https://www.sciencedirect.com/science/article/pii/S2590123020300128

# Series Caóticas

3. Usar el algortimo del juego de caos de tres vértices para visualizar una serie caótica generada por la ecuación logística, (2) el mapeo de Henón y (3) la ecuación de Lorentz.

## Ecuación Logística
"""

def logistic_map(r, x, N):
    series = []
    for _ in range(N):
        x = r * x * (1 - x)
        series.append(x)
    return series

# Definimos los parámetros
r = 3.9
x0 = 0.1
N = 10000

logistic_series = logistic_map(r, x0, N)

# Usamos el juego del caos para la ecuación logística

# Definimos los vértices
v = [[0,0],[1,0],[0.5,0.5*np.sqrt(3)]]

# Normalizamos en caso de ser necesario
if np.max(logistic_series) > 1 or np.min(logistic_series) < 0:
    print("Normalizing logistic series for chaos game...")
    logistic_series_normalized = (logistic_series - np.min(logistic_series)) / (np.max(logistic_series) - np.min(logistic_series))
else:
    logistic_series_normalized = logistic_series

# Creamos una función del juego del caos para la ecuacion logistica

def juego_caos_logistic(N, v, series):
  x, y = random.random(), random.random()
  lista_x = []
  lista_y = []
  for i in range(N):
    # Usamos la serie para escoger el valor del vértice
    series_val = series[i % len(series)]
    if series_val < 1/3:
        rx, ry = v[0]
    elif series_val < 2/3:
        rx, ry = v[1]
    else:
        rx, ry = v[2]

    # Aplicamos el punto medio
    x = (rx + x)/2
    y = (ry + y)/2

    lista_x.append(x)
    lista_y.append(y)
  return lista_x, lista_y

lista_x, lista_y = juego_caos_logistic(N, v, logistic_series_normalized)

# Graficamos los puntos generados
plt.figure(figsize=(8, 8))
plt.title('Juego del Caos para la Ecuación Logística')
plt.scatter(lista_x, lista_y, s=1, alpha=0.5)
plt.show()

"""## Mapeo de Henón"""

def henon_map(x, y, a, b, N):
    series_x = []
    series_y = []
    for _ in range(N):
        x_new = 1 - a * x**2 + y
        y_new = b * x
        x, y = x_new, y_new
        series_x.append(x)
        series_y.append(y)
    return series_x, series_y

# Definimos los parámetros
a = 1.4
b = 0.3
x0 = 0.1
y0 = 0.1
N = 10000

henon_series_x, henon_series_y = henon_map(x0, y0, a, b, N)

# Usamos el juego del caos para el Mapeo de Henón

# Definimos los vértices
v = [[0,0],[1,0],[0.5,0.5*np.sqrt(3)]]

# Normalizamos los valores de la serie
min_val = min(np.min(henon_series_x), np.min(henon_series_y))
max_val = max(np.max(henon_series_x), np.max(henon_series_y))

henon_series_x_normalized = (henon_series_x - min_val) / (max_val - min_val)
henon_series_y_normalized = (henon_series_y - min_val) / (max_val - min_val)


# Creamos una función del juego del caos para el mapeo de Henón

def juego_caos_henon(N, v, series_x, series_y):
  x, y = random.random(), random.random()
  lista_x = []
  lista_y = []
  for i in range(N):
    # Usamos las series para escoger el valor del vértice
    series_val_x = series_x[i % len(series_x)]
    series_val_y = series_y[i % len(series_y)]

    if series_val_x < 0.5:
        rx, ry = v[0]
    elif series_val_y < 0.5:
        rx, ry = v[1]
    else:
        rx, ry = v[2]


    # Aplicamos el punto medio
    x = (rx + x)/2
    y = (ry + y)/2

    lista_x.append(x)
    lista_y.append(y)
  return lista_x, lista_y

lista_x_henon, lista_y_henon = juego_caos_henon(N, v, henon_series_x_normalized, henon_series_y_normalized)

# Graficamos los puntos generados
plt.figure(figsize=(8, 8))
plt.title('Juego del Caos para el Mapeo de Henón')
plt.scatter(lista_x_henon, lista_y_henon, s=1, alpha=0.5)
plt.show()

"""## Ecuación de Lorentz"""

# creamos la función de la ecuacion de lorenz
def lorenz(x, y, z, sigma, rho, beta, delta):
    dx = sigma * (y - x)
    dy = x * (rho - z) - y
    dz = x * y - beta * z
    x = x + delta*dx
    y = y + delta*dy
    z = z + delta*dz
    return x, y, z

# inicializamos parámetros
sigma =10
rho =30
beta = 2.6666
N_steps = 5000
delta = 0.011

# Generamos las series de Lorenz
# Condiciones iniciales
x, y, z = 0.1, 0.1, 0.1
lorentz_series_x = []
lorentz_series_y = []
lorentz_series_z = []

for _ in range(N_steps):
    x, y, z = lorenz(x, y, z, sigma, rho, beta, delta)
    lorentz_series_x.append(x)
    lorentz_series_y.append(y)
    lorentz_series_z.append(z)

# Convertimos las listas en matrices
lorentz_series_x = np.array(lorentz_series_x)
lorentz_series_y = np.array(lorentz_series_y)
lorentz_series_z = np.array(lorentz_series_z)

# Usamos el juego del caos para la Ecuación de Lorentz (usando solo la serie x)

# Definimos los vértices
v = [[0,0],[1,0],[0.5,0.5*np.sqrt(3)]]

# Normalizamos en caso de ser necesario
if np.max(lorentz_series_x) > 1 or np.min(lorentz_series_x) < 0:
    print("Normalizing Lorentz x-series for chaos game...")
    lorentz_series_x_normalized = (lorentz_series_x - np.min(lorentz_series_x)) / (np.max(lorentz_series_x) - np.min(lorentz_series_x))
else:
    lorentz_series_x_normalized = lorentz_series_x

# Creamos una función del juego del caos para la ecuacion de Lorentz (usando solo la serie x)

def juego_caos_lorentz_x(N, v, series_x):
  x, y = random.random(), random.random()
  lista_x = []
  lista_y = []
  for i in range(N):
    # Usamos la serie x para escoger el valor del vértice
    series_val_x = series_x[i % len(series_x)]
    if series_val_x < 1/3:
        rx, ry = v[0]
    elif series_val_x < 2/3:
        rx, ry = v[1]
    else:
        rx, ry = v[2]

    # Aplicamos el punto medio
    x = (rx + x)/2
    y = (ry + y)/2

    lista_x.append(x)
    lista_y.append(y)
  return lista_x, lista_y

# Definimos el número de puntos para el juego del caos
N_chaos = 1000000

lista_x_lorentz, lista_y_lorentz = juego_caos_lorentz_x(N_chaos, v, lorentz_series_x_normalized)

# Graficamos los puntos generados
plt.figure(figsize=(8, 8))
plt.title('Juego del Caos para la Ecuación de Lorentz (Serie X)')
plt.scatter(lista_x_lorentz, lista_y_lorentz, s=1, alpha=0.5)
plt.show()